### ISSUE TITLE
Load private models from Replicate

### ISSUE THREAD

**Issue by ashakoen** [rtuszik/replicate-flux-lora#6]
Thanks for creating this app! When I tried generate images using a Private fine-tune model on Replicate, I wasn't able to do so. I updated the code allow this feature. It looks like you're actively developing, so I'm happy to submit a PR with my changes, or just wait until you implement it.

**Comment by rtuszik** [comment]
Hi there,
I appreciate you checking out this project. Could you let me know what exactly didn't work?

I use it almost exclusively for private models, but the process of adding them to the app is a bit clunky right now. I just pushed some changes to the docker-compose as well, as I had some errors there.

Feel free to PR if you have any fixes!

**Comment by ashakoen** [comment]
Ok, cool. When running under Docker, I had to specifically define the api_token in replicate_api.py:
```python
replicate.api_token = os.getenv("REPLICATE_API_TOKEN")
```

**Comment by rtuszik** [comment]
Yes, my instructions there were a bit faulty. If you specify a .env file within docker,  python-dotenv will retrieve the API Token from the .env file.

Please let me know if this is working for you with the latest version of the image.

**Comment by ashakoen** [comment]
Yep, latest version works as is. I'm building vs. using the pre-made image, but all the same it works. Thanks!

**Comment by rtuszik** [comment]
Great to hear!

Let me know if you encounter any issues or have any further ideas. Im mainly working on fixing the UI right now.
